import{useEffect,useMemo,useState}from'react';import{Baby,BookOpen,Camera,ChevronLeft,ClipboardList,Clock3,Droplets,Heart,Home,LogOut,Mail,Milk,Plus,Save,ShieldCheck,Smile,Soup,Sparkles,Users}from'lucide-react';import{configured,supabase}from'./supabase';
const demo=[{id:'1',first_name:'Eleanor'},{id:'2',first_name:'Lochlan'},{id:'3',first_name:'Logan'},{id:'4',first_name:'Jay'}];
const actions=[[Soup,'Meal'],[Milk,'Bottle'],[Clock3,'Nap'],[Droplets,'Diaper'],[Sparkles,'Activity'],[Camera,'Photo'],[Smile,'Mood'],[BookOpen,'Notes']];
export default function App(){const[children,setChildren]=useState(demo),[selected,setSelected]=useState(null),[entries,setEntries]=useState([]),[notice,setNotice]=useState(''),[session,setSession]=useState(null),[authReady,setAuthReady]=useState(!configured),[authMode,setAuthMode]=useState('create'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authBusy,setAuthBusy]=useState(false),[authMessage,setAuthMessage]=useState('');const today=useMemo(()=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date()),[]);
useEffect(()=>{if(!configured)return;supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);setAuthReady(true)});return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(!configured||!session)return;(async()=>{const{data,error}=await supabase.from('children').select('id,first_name,preferred_name,active').eq('active',true).order('first_name');if(error){setNotice('Administrator sign-in is active. The children database will be created next.');setChildren(demo)}else setChildren(data||[]);})();},[session]);
const name=c=>c.preferred_name||c.first_name;function add(label){setEntries(e=>[{id:crypto.randomUUID(),label,time:new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date())},...e]);setNotice(label+' entry started for '+name(selected)+'.');}
async function submitAuth(e){e.preventDefault();setAuthBusy(true);setAuthMessage('');try{if(authMode==='create'){const{data,error}=await supabase.auth.signUp({email,password});if(error)throw error;if(data.session)setAuthMessage('Administrator account created. You are signed in.');else setAuthMessage('Account created. Please check your email and confirm your address, then return here to sign in.')}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setAuthMessage('Welcome back, Maggie.')}}catch(error){setAuthMessage(error.message||'Something went wrong. Please try again.')}finally{setAuthBusy(false)}}
async function signOut(){await supabase.auth.signOut();setSelected(null);setNotice('');setAuthMessage('You have signed out.');}
if(!configured)return <main className="app"><header><div className="logo"><Home/></div><div><small>Family daycare</small><h1>Maggie’s House</h1></div></header><section className="hero"><span>{today}</span><h2>Good day, Maggie!</h2><p>Everything you need for today’s care is in one peaceful place.</p><Heart className="heart"/></section><div className="banner"><Sparkles/><div><b>Beautiful preview mode</b><small>Your database connection will be added next.</small></div></div></main>;
if(!authReady)return <main className="app auth-shell"><section className="auth-card"><div className="auth-mark"><ShieldCheck/></div><h1>Maggie’s House</h1><p>Preparing your secure administrator access…</p></section></main>;
if(!session)return <main className="app auth-shell"><section className="auth-card"><div className="auth-mark"><ShieldCheck/></div><small>Family daycare administrator</small><h1>{authMode==='create'?'Create your administrator account':'Administrator sign in'}</h1><p>{authMode==='create'?'This first account will be used by you to manage Maggie’s House.':'Sign in to open your daycare dashboard.'}</p><form onSubmit={submitAuth}><label>Email address</label><div className="input-wrap"><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Your email address" required/></div><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters" minLength="6" required/><button className="save" disabled={authBusy}>{authBusy?'Please wait…':authMode==='create'?'Create Administrator Account':'Sign In'}</button></form>{authMessage&&<div className="notice auth-notice">{authMessage}</div>}<button className="text-button" onClick={()=>{setAuthMode(authMode==='create'?'signin':'create');setAuthMessage('')}}>{authMode==='create'?'I already have an account — Sign in':'Create the first administrator account'}</button></section></main>;
if(selected)return <main className="app"><header><button className="icon" onClick={()=>setSelected(null)}><ChevronLeft/></button><div><small>Today’s care</small><h1>{name(selected)}</h1></div><div className="avatar"><Baby/></div></header><section className="hero"><span>{today}</span><h2>What would you like to record?</h2><p>Tap a button during the day. We’ll turn the entries into a parent report.</p></section><section className="grid">{actions.map(([Icon,label])=><button key={label} onClick={()=>add(label)}><i><Icon/></i><b>{label}</b></button>)}</section>{notice&&<div className="notice">{notice}</div>}<section className="card"><div className="title"><div><small>Daily timeline</small><h2>Today’s entries</h2></div><ClipboardList/></div>{entries.length?entries.map(x=><div className="entry" key={x.id}><span>{x.time}</span><b>{x.label}</b></div>):<p className="empty">No entries yet. Tap one of the care buttons above.</p>}</section><button className="save" onClick={()=>setNotice('Daily report saved for '+name(selected)+'.')}><Save/>Save Daily Report</button></main>;
return <main className="app"><header><div className="logo"><Home/></div><div><small>Family daycare</small><h1>Maggie’s House</h1></div><button className="icon" onClick={signOut} title="Sign out"><LogOut/></button></header><section className="hero"><span>{today}</span><h2>Good day, Maggie!</h2><p>Everything you need for today’s care is in one peaceful place.</p><Heart className="heart"/></section><div className="banner"><ShieldCheck/><div><b>Administrator signed in</b><small>{session.user.email}</small></div></div>{notice&&<div className="notice">{notice}</div>}<section className="card"><div className="title"><div><small>Present today</small><h2>Today’s children</h2></div><em>{children.length}</em></div>{children.map(c=><button className="child" key={c.id} onClick={()=>{setSelected(c);setEntries([]);setNotice('')}}><div className="avatar"><Baby/></div><div><b>{name(c)}</b><small>Open today’s care record</small></div><strong>Open</strong></button>)}<button className="add" onClick={()=>setNotice('The Add Child form is coming in the next step.')}><Plus/>Add Child</button></section><nav><button className="active"><Home/><small>Home</small></button><button><ClipboardList/><small>Reports</small></button><button><Camera/><small>Photos</small></button><button><Users/><small>Families</small></button></nav></main>}
